embeddings:
  UMAP:
    x: umap_x
    y: umap_y
  default: UMAP
color-columns:
  categorical:
    - donor
    # - cluster
    # - plate
    # - compound
    # - concentration
    # - moa
  # numerical:
  #   - id
image-column:
  donor
tooltip-columns:
  - donor
  - cluster
plots:
  glyph_size: 2.0