embeddings:
  UMAP:
    x: umap_x
    y: umap_y
  default: UMAP
color-columns:
  categorical:
    - roi
    # - channel
    # - plate
    # - compound
    # - concentration
    # - moa
  # numerical:
  #   - id
image-column:
  image_names
tooltip-columns:
  - roi
  # - channel
plots:
  glyph_size: 2.0