embeddings:
  UMAP:
    x: umap_x
    y: umap_y
  default: UMAP
color-columns:
  categorical:
    - roi
    # - channel
    # - plate
    # - compound
    # - concentration
    # - moa
  # numerical:
  #   - id
image-columns:
  - AF488_imagepath
  - AF555_imagepath
  - AF647_imagepath
  - AF750_imagepath
  - DAPI_imagepath
tooltip-columns:
  - roi
  # - channel
plots:
  glyph_size: 2.0