embeddings:
  UMAP:
    x: umap_x
    y: umap_y
  default: UMAP
color-columns:
  categorical:
    - donor
    # - channel
    # - plate
    # - compound
    # - concentration
    # - moa
  # numerical:
  #   - id
image-columns:
  - c1_imgpath
  - c2_imgpath
  - c3_imgpath
  - c4_imgpath
  - c5_imgpath
centroid-x-column:
  centroid_x
centroid-y-column:
  centroid_y
tooltip-columns:
  - donor
  # - channel
plots:
  glyph_size: 1.0